name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push for Linux builds
        uses: docker/build-push-action@v4
        with:
          file: ./linux.Dockerfile
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hello:linux-latest
          push: true
      - name: Build and push for Windows builds
        uses: docker/build-push-action@v4
        with:
          file: ./windows.Dockerfile
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hello:windows-latest
          push: true
      - name: Copy binaries from container to host
        run: |
          docker ps
          docker ps -q
          docker ps -q --filter ancestor=ubuntu:16.04
          docker ps -q --filter ancestor=ubuntu:22.04

          linux_id=$(docker ps -q --filter ancestor=ubuntu:16.04 | xargs)
          windows_id=$(docker ps -q --filter ancestor=ubuntu:22.04 | xargs)

          copy_over() {
              local build_path=$( \
                  docker exec $1 ls -R / | \
                  grep "hello/target/$2/release:" | \
                  sed -e "s/:.*//" \
              )
              docker cp \
                  "$1:$build_path/$3" \
                  "$4"
          }

          copy_over $linux_id "x86_64-unknown-linux-gnu" "hello" "hello-x86_64-linux"
          copy_over $linux_id "i686-unknown-linux-gnu" "hello" "hello-x86-linux"
          copy_over $linux_id "aarch64-unknown-linux-gnu" "hello" "hello-aarch64-linux"
          copy_over $linux_id "armv7-unknown-linux-gnueabi" "hello" "hello-arm-linux"
          copy_over $windows_id "x86_64-pc-windows-gnu" "hello.exe" "hello-x86_64-windows.exe"
          copy_over $windows_id "i686-pc-windows-gnu" "hello.exe" "hello-x86-windows.exe"
      - name: Upload x86_64-unknown-linux-gnu artifact
        uses: actions/upload-artifact@v3
        with:
          name: hello-x86_64-linux
          path: hello-x86_64-linux
          retention-days: 5
      - name: Upload i686-unknown-linux-gnu artifact
        uses: actions/upload-artifact@v3
        with:
          name: hello-x86-linux
          path: hello-x86-linux
          retention-days: 5
      - name: Upload aarch64-unknown-linux-gnu artifact
        uses: actions/upload-artifact@v3
        with:
          name: hello-aarch64-linux
          path: hello-aarch64-linux
          retention-days: 5
      - name: Upload armv7-unknown-linux-gnu artifact
        uses: actions/upload-artifact@v3
        with:
          name: hello-arm-linux
          path: hello-arm-linux
          retention-days: 5
      - name: Upload x86_64-pc-windows-gnu artifact
        uses: actions/upload-artifact@v3
        with:
          name: hello-x86_64-windows.exe
          path: hello-x86_64-windows.exe
          retention-days: 5
      - name: Upload i686-pc-windows-gnu artifact
        uses: actions/upload-artifact@v3
        with:
          name: hello-x86-windows.exe
          path: hello-x86-windows.exe
          retention-days: 5
