name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hello:latest
      - name: Copy files from Docker image to main filesystem
        run: |
          docker run --rm --entrypoint=cat --platform=linux/amd64 ubuntu:16.04 /hello/target/x86_64-unknown-linux-gnu/release/hello > hello-x86_64-linux
          docker run --rm --entrypoint=cat --platform=linux/amd64 ubuntu:16.04 /hello/target/aarch64-unknown-linux-gnu/release/hello > hello-aarch64-linux
          docker run --rm --entrypoint=cat --platform=linux/amd64 ubuntu:16.04 /hello/target/x86_64-pc-windows-gnu/release/hello > hello-x86_64-windows.exe
      - name: Upload x86_64-unknown-linux-gnu artifact
        uses: actions/upload-artifact@v3
        with:
          name: hello-x86_64-linux
          path: hello-x86_64-linux
      - name: Upload aarch64-unknown-linux-gnu artifact
        uses: actions/upload-artifact@v3
        with:
          name: hello-aarch64-linux
          path: hello-aarch64-linux
      - name: Upload x86_64-pc-windows-gnu artifact
        uses: actions/upload-artifact@v3
        with:
          name: hello-x86_64-windows.exe
          path: hello-x86_64-windows.exe
